### ISSUE TITLE
mkvtoolnix check crashes on DVDs

### ISSUE THREAD

**Issue by werrpy** [werrpy/vdator#29]
https://pastebin.com/RtKHbXpR

```
Traceback (most recent call last):
  File "/home/user/vdator/venv/vdator/main.py", line 122, in on_message
    reply += checker.check_mkvmerge()
  File "/home/user/vdator/venv/vdator/checker.py", line 268, in check_mkvmerge
    mediainfo_version_name = re.search(version_name_regex_mediainfo, self.mediainfo['general'][0]['writing_application']).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by werrpy** [comment]
Closed by 6c3b20459ae121f358c47474a51de1075b172e5f
